name: deploy example game to Pages

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 允许后续代码读写仓库
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod- uses: actions/checkout@v4
      - name: download tweego
        run: |
          mkdir tools
          curl -L -o tools/tweego.zip https://github.com/Raven-Book/twee-example/releases/download/tweego-file/tweego-2.1.1-linux-x64.zip
          unzip tools/tweego.zip -d tools/
      
      - name: set execute permissions
        run: chmod +x tools/tweego

      - name: add tweego to PATH
        run: echo "${{ github.workspace }}/tools" >> $GITHUB_PATH
      
      - name: build game 
        run: tweego ./assets ./story -o dist/index.html

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist